# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.SourcesDirectory)/run-container/'
    artifact: 'run-container'
  displayName: Publish run-container Scripts  
- task: Docker@2
  inputs:
    containerRegistry: 'customerapiloadacr'
    repository: 'customer-api-load-test'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'